In [2]:
import numpy

arr = numpy.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

type(arr)

[1 2 3 4 5]


numpy.ndarray

In [5]:
print(np.__version__)

1.19.5


In [7]:
import numpy as np

arr = np.array((1,2,3,4,5))

print(arr)

type(arr)

[1 2 3 4 5]


numpy.ndarray

In [8]:
arr=np.array(42)
print(42)

42


In [9]:
arr=np.array([[1,2,3],[4,5,6]])# 2D array
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])# 3D array
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [16]:
import numpy as np#ndexing

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[3])

4


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2]+ arr[3])

7


In [19]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5,6,7,8]])

print(arr[0,1])

2


In [20]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5,6,7,8]])#2D

print(arr[1,3])

8


In [21]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])#3D

print(arr[0, 1, 2])

6


In [22]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5,6,7,8]])#2D   -ve indexing

print(arr[1,-1])

8


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4,5,6,7,8])#2D

print(arr[1:3])

[2 3]


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4,5,6,7,8])#2D

print(arr[:6])

[1 2 3 4 5 6]


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4,5,6,7,8])#2D

print(arr[-3:-1])

[6 7]


In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4,5,6,7,8])#2D

print(arr[1:3:2])

[2]
