In [1]:
import numpy as np    #data type

arr=np.array([1,2,3,4])

print(arr.dtype)

int32


In [2]:
import numpy as np    #data type--->i- integer,f-float,c-complex,S-string...etc

arr=np.array(["banana","mango","orange"])

print(arr.dtype)

<U6


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [5]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [6]:
import numpy as np

In [7]:
arr=np.array([1.2,1.3,1.4])

In [8]:
arr1=arr.astype(bool)

In [9]:
print(arr1)
print(arr1.dtype)

[ True  True  True]
bool


Copy & View in array


In [11]:
arr=np.array([1,2,3,4])
x=arr.view()
arr[0]=42

print(arr)
print(x)

[42  2  3  4]
[42  2  3  4]


In [12]:
arr=np.array([1,2,3,4])
x=arr.copy()
arr[0]=42

print(arr)
print(x)

[42  2  3  4]
[1 2 3 4]


In [18]:
arr=np.array([1,2,3,4])
x=arr.view()
x[0]=31

print(arr)
print(x)

[31  2  3  4]
[31  2  3  4]


In [19]:
x=arr.copy()
y=arr.view()

In [20]:
print(x.base)

None


In [17]:
print(y.base)

[31  2  3  4]


In [21]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [23]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [24]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [28]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [29]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [30]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
