##Shape


In [3]:
import numpy as np

arr=np.array([[1,2,3,4],[6,7,8,9]])

print(arr.shape)

(2, 4)


In [ ]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [4]:
arr=np.array([1,2,3,4],ndmin=5)

print(arr)

[[[[[1 2 3 4]]]]]


In [5]:
print(arr.shape)

(1, 1, 1, 1, 4)


##Reshaping

In [22]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 element
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
newarr=arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
print(newarr.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
arr=np.array([1,2,3,4,5,6,7,8])

newarr=arr.reshape(2,2,-1)

print(arr)

[1 2 3 4 5 6 7 8]


In [28]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

newarr=arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6 7 8]


#Ierating

In [31]:
arr=np.array([1,2,3])#1 dimension

for x in arr:
    print(x)

1
2
3


In [32]:
arr=np.array([[1,2,3],[4,5,6]])# 2 dimension

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [38]:
arr=np.array([[1,2,3],[4,5,6]])# 2 dimension

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [41]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [42]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [44]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [45]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):#Iterating Arrays Using nditer()
    print(x)

1
2
3
4
5
6
7
8


In [48]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr[1,3])

8


In [49]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [52]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [53]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [54]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
